#include "define.h"

#include <stdio.h>
#include <string.h>

#include "oled.h"
#include "font.h"


#include "nrf_delay.h"
#include "nrf_gpio.h"
#include "common.h"
#ifdef GC_NRF52_TWI
	#include "nrf_drv_twi.h"
#elif defined GC_NRF51_TWI
	#include "twi_master.h"
#endif /* GC_NRF52_TWI */

 #ifdef GC_NRF52_TWI
extern const nrf_drv_twi_t m_twi_master_1;
#endif

char	m_oled_active=0;

void Enable_OLED(void)
{
	m_oled_active=1;
}

void Disable_OLED(void)
{
	m_oled_active=0;
}

char Get_OLED_Power_Status(void)
{
	return m_oled_active;
}


void Init_OLED_PORT(void)
{
#ifdef GC_COACH_FIT_PCB
	nrf_gpio_cfg_output(OLED_RESET_PIN);
	nrf_gpio_pin_clear(OLED_RESET_PIN);
#elif defined GC_COACH_FIT_DK52
	nrf_gpio_cfg_output(OLED_POWER);
	nrf_gpio_cfg_output(OLED_RESET_PIN);
	nrf_gpio_pin_clear(OLED_POWER);
	nrf_gpio_pin_clear(OLED_RESET_PIN);
#else
#endif

	
	
	// KEY INPUT
	 //nrf_gpio_cfg_input(KEY_INPUT, NRF_GPIO_PIN_NOPULL);


/*
	m_spi_base_address = spi_master_init((SPIModuleNumber)SPI0, SPI_MODE0,  false );
	if (m_spi_base_address == 0)
	{
		printf("\n\r spi init fail.");
	}
*/
	
}

void OLED_Write_Command(unsigned char cmd)
{
	unsigned char w2_data[2];
	uint32_t	err_code=0;

	if(!m_oled_active)
		return;

	w2_data[0]=0;
	w2_data[1] =cmd;

#ifdef GC_NRF52_TWI
	err_code = nrf_drv_twi_tx(&m_twi_master_1, (OLED_I2C_ADDRESS >> 1), w2_data, 2, false);
	if (err_code != NRF_SUCCESS)
	{
#ifndef _FIT_ETRI_TEST_
			printf("\n\r OLED TWI write error(error code %d)", err_code);
#endif
	}
#elif defined GC_NRF51_TWI 	
	if(twi_master_transfer(OLED_I2C_ADDRESS, w2_data, 2, TWI_ISSUE_STOP)==false)
	{
		//printf("\n\rOLED_Write_Command error : i2c write");
	}
#endif /* GC_NRF52_TWI */
}

void OLED_Write_Data(unsigned char data)
{
	unsigned char w2_data[2];
	uint32_t	err_code=0;

	if(!m_oled_active)
		return;

	w2_data[0]=0x40;
	w2_data[1] =data;

#ifdef GC_NRF52_TWI
	err_code = nrf_drv_twi_tx(&m_twi_master_1, (OLED_I2C_ADDRESS >> 1), w2_data, 2, false);
	if (err_code != NRF_SUCCESS)
	{
#ifndef _FIT_ETRI_TEST_
			printf("\n\r OLED TWI write error(error code %d)", err_code);
#endif
	}
#elif defined GC_NRF51_TWI 		
	if(twi_master_transfer(OLED_I2C_ADDRESS, w2_data, 2, TWI_ISSUE_STOP)==false)
	{
		//printf("\n\rOLED_Write_Data error : i2c write");
	}
#endif /* GC_NRF52_TWI */
}


void OLED_Clear(void)
{
	OLED_Clear_Line(0);
	OLED_Clear_Line(1);
	OLED_Clear_Line(2);
	OLED_Clear_Line(3);
	OLED_Clear_Line(4);
	OLED_Clear_Line(5);
}	


void OLED_Clear_Line(int n)
{
	int i;

	if(n>5)
		n=3;

	if(n<0)
		n=0;

	OLED_Write_Command(0xB0+n);
	OLED_Write_Command(0x12);
	OLED_Write_Command(0x0);
	for(i=0;i<64;i++)
		OLED_Write_Data(0);

}

extern const unsigned char ubFontNum2[52];

#ifdef GC_COACH_FIT_PCB
void OLED_Power(int onoff)
{
	if(onoff)
	{
		nrf_gpio_pin_clear(OLED_RESET_PIN);
#ifdef GC_COACH_FIT_DK52
	 	nrf_gpio_pin_set(OLED_POWER);
#endif 
		nrf_delay_ms(100);
	 	nrf_gpio_pin_set(OLED_RESET_PIN);

		nrf_delay_ms(100);

		Enable_OLED();

		OLED_Write_Command(0xAE); //Set Display Off

		OLED_Write_Command(0xD5); //Set Display Clock Divide Ratio/Oscillator Frequency
		OLED_Write_Command(0x80);
		OLED_Write_Command(0xA8); //Set Multiplex Ratio
		OLED_Write_Command(0x2F);
		OLED_Write_Command(0xD3); //Set Display Offset
		OLED_Write_Command(0x00);
		OLED_Write_Command(0x40); //Set Display Start Line
		OLED_Write_Command(0x8D); //Set Charge Pump
		OLED_Write_Command(0x14); //VCC Generated by Internal DC/DC Circuit
		OLED_Write_Command(0xA1); //Set Segment Re-Map
		OLED_Write_Command(0xC8); //Set COM Output Scan Direction
		OLED_Write_Command(0xDA); //Set COM Pins Hardware Configuration
		OLED_Write_Command(0x12);
		OLED_Write_Command(0x81); //Set Contrast Control
		OLED_Write_Command(0xCF);
		OLED_Write_Command(0xD9); //Set Pre-Charge Period
		OLED_Write_Command(0x22);
		OLED_Write_Command(0xDB); //Set VCOMH Deselect Level
		OLED_Write_Command(0x00);
		OLED_Write_Command(0xA4); //Set Entire Display On/Off
		OLED_Write_Command(0xA6); //Set Normal/Inverse Display

		OLED_Write_Command(0xAF); //Set Display On

	}
	else
	{
		OLED_Clear();
		Disable_OLED();
	 	nrf_gpio_pin_clear(OLED_RESET_PIN);
#ifdef GC_COACH_FIT_DK52
	 	nrf_gpio_pin_clear(OLED_POWER);
#endif 
	
		//printf("\n\rOLED_Power OFF\n\r");
	}
}
#elif defined GC_COACH_FIT_DK52
void OLED_Power(int onoff)
{
	if(onoff)
	{
		nrf_gpio_pin_clear(OLED_RESET_PIN);
#ifdef GC_COACH_FIT_DK52
	 	nrf_gpio_pin_set(OLED_POWER);
#endif 
		nrf_delay_ms(100);
	 	nrf_gpio_pin_set(OLED_RESET_PIN);

		nrf_delay_ms(100);

		Enable_OLED();

		OLED_Write_Command(0xAE);     //Set Display Off 

		OLED_Write_Command(0x00);     /*set lower column address*/	
		OLED_Write_Command(0x12);     /*set higher column address*/
		 
		OLED_Write_Command(0x00);     /*set display start line*/
		OLED_Write_Command(0xb0);		/*set page address*/


		OLED_Write_Command(0x81); /*contract control*/
		OLED_Write_Command(0x4f); /*128*/
		OLED_Write_Command(0xA1); /*set segment remap*/
		OLED_Write_Command(0xA6); /*normal / reverse*/
		OLED_Write_Command(0xA8); /*multiplex ratio*/
		OLED_Write_Command(0x1F); /*duty = 1/32*/
		OLED_Write_Command(0xC8); /*Com scan direction*/
		OLED_Write_Command(0xD3); /*set display offset*/
		OLED_Write_Command(0x00);
		OLED_Write_Command(0xD5); /*set osc division*/
		OLED_Write_Command(0x80);
		OLED_Write_Command(0xD9); /*set pre-charge period*/
		OLED_Write_Command(0x1f);
		OLED_Write_Command(0xDA); /*set COM pins*/
		OLED_Write_Command(0x12);
		OLED_Write_Command(0xdb); /*set vcomh*/
		OLED_Write_Command(0x40);
		OLED_Write_Command(0x8d); /*set charge pump enable*/

		OLED_Write_Command(0x10);		// external
		//OLED_Write_Command(0x14);		// internal

		
		
		OLED_Write_Command(0xAF); /*display ON*/

		//printf("\n\rOLED_Power ON\n\r");
		
	}
	else
	{
		OLED_Clear();
		Disable_OLED();
	 	nrf_gpio_pin_clear(OLED_RESET_PIN);
#ifdef GC_COACH_FIT_DK52
	 	nrf_gpio_pin_clear(OLED_POWER);
#endif 
	
		//printf("\n\rOLED_Power OFF\n\r");
	}
}
#else
#endif 
